app.services.auth=${AUTH_SERVICE_URL}
app.services.user=${USER_SERVICE_URL}
app.services.order=${ORDER_SERVICE_URL}
app.services.payment=${PAYMENT_SERVICE_URL}

jwt.access.secret=${JWT_ACCESS_SECRET}
marketplace.swagger-path=/api/v3/api-docs